In [64]:
print("hello world")

hello world


In [65]:
import numpy as np

In [66]:
x = 5
x = x**3 - 25
print(x)

100


In [67]:
y = np.linspace(0.0, 10.0, 11)
print(y[0], y[1], y[-1])

0.0 1.0 10.0


In [68]:
print(y[1:5])
print(y[5:])

[1. 2. 3. 4.]
[ 5.  6.  7.  8.  9. 10.]


In [69]:
print(y[y>3])

[ 4.  5.  6.  7.  8.  9. 10.]


In [70]:
a = np.array([0, 1, 2, 3])
b = np.array([0, 15, 30, 45])
print(2*a + a*b)

[  0  17  64 141]


In [71]:
z = 14.35244
print("%d"%(z))
print("%.3f"%(z))
print("%.4e"%(z))
print("%05d"%(z))

14
14.352
1.4352e+01
00014


In [1]:
def myfunc1(x):
    return(x**2)
print(myfunc1(2.7))

7.290000000000001
